repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Use the latest version available
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7  # Use the latest version available
    hooks:
      - id: autopep8
        args: ["--in-place", "--max-line-length=79"]  # Add the --in-place argument here

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        args: ["--maxfail=0", "--disable-warnings"]
        additional_dependencies: []
